
package com.cold.mtservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-01-04T12:56:14.599+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class IMachineTranslationService_BasicHttpBindingIMachineTranslationService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "MachineTranslationService");

    private IMachineTranslationService_BasicHttpBindingIMachineTranslationService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MachineTranslationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MachineTranslationService ss = new MachineTranslationService(wsdlURL, SERVICE_NAME);
        IMachineTranslationService port = ss.getBasicHttpBindingIMachineTranslationService();  
        
        {
        System.out.println("Invoking translate...");
        MachineTranslationParameter _translate_translationParameter = null;
        MachineTranslationResult _translate__return = port.translate(_translate_translationParameter);
        System.out.println("translate.result=" + _translate__return);


        }

        System.exit(0);
    }

}
