package com.cold.mtservice.client;



import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-01-04T12:56:14.673+08:00
 * Generated source version: 2.7.11
 * 
 */
@org.springframework.stereotype.Service
@WebServiceClient(name = "MachineTranslationService", 
                  wsdlLocation = "http://192.168.3.113:8082/Transformer/services/MachineTranslationService?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class MachineTranslationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "MachineTranslationService");
    public final static QName BasicHttpBindingIMachineTranslationService = new QName("http://tempuri.org/", "BasicHttpBinding_IMachineTranslationService");
    static {
        URL url = null;
        try {
            //WebserviceConfig config = SpringContextUtil.getBean("webserviceConfig", WebserviceConfig.class);
            //url = new URL(config.getMtWsdl());
            url = new URL("http://192.168.3.113:8082/Transformer/services/MachineTranslationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MachineTranslationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.3.113:8082/Transformer/services/MachineTranslationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MachineTranslationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MachineTranslationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineTranslationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MachineTranslationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MachineTranslationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MachineTranslationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IMachineTranslationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMachineTranslationService")
    public IMachineTranslationService getBasicHttpBindingIMachineTranslationService() {
        return super.getPort(BasicHttpBindingIMachineTranslationService, IMachineTranslationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMachineTranslationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMachineTranslationService")
    public IMachineTranslationService getBasicHttpBindingIMachineTranslationService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIMachineTranslationService, IMachineTranslationService.class, features);
    }

}
